import {
  UserProfile,
  KPIMetric,
  TransactionItem,
  ExpenseCategoryItem,
  CashFlowPoint,
  GoalItem,
  LiabilityItem,
  SubscriptionItem,
  AlertItem,
  AIInsightItem,
  ChatMessage,
} from "@/types";

export const MOCK_USER: UserProfile = {
  id: "user-1",
  name: "Alex Morgan",
  email: "alex.morgan@finpilot.ai",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  healthScore: 78,
};

export const MOCK_KPIS: KPIMetric[] = [
  {
    title: "Monthly Income",
    value: 85000,
    formattedValue: "₹85,000",
    changePercent: 5.2,
    trend: "up",
    subtitle: "Primary salary + freelance",
    iconName: "TrendingUp",
  },
  {
    title: "Monthly Expenses",
    value: 54200,
    formattedValue: "₹54,200",
    changePercent: -3.8,
    trend: "down",
    subtitle: "63.7% of total income",
    iconName: "CreditCard",
  },
  {
    title: "Monthly Savings",
    value: 30800,
    formattedValue: "₹30,800",
    changePercent: 14.5,
    trend: "up",
    subtitle: "36.3% savings rate",
    iconName: "PiggyBank",
  },
  {
    title: "Total Debt",
    value: 640000,
    formattedValue: "₹6,40,000",
    changePercent: -2.1,
    trend: "down",
    subtitle: "3 Active Liabilities",
    iconName: "Landmark",
  },
];

export const MOCK_CASH_FLOW: CashFlowPoint[] = [
  { month: "Jan", income: 82000, expenses: 51000, projectedBalance: 31000 },
  { month: "Feb", income: 82000, expenses: 56500, projectedBalance: 56500 },
  { month: "Mar", income: 85000, expenses: 52000, projectedBalance: 89500 },
  { month: "Apr", income: 85000, expenses: 58000, projectedBalance: 116500 },
  { month: "May", income: 85000, expenses: 54200, projectedBalance: 147300 },
  { month: "Jun (Est)", income: 85000, expenses: 53000, projectedBalance: 179300 },
  { month: "Jul (Est)", income: 88000, expenses: 54000, projectedBalance: 213300 },
];

export const MOCK_EXPENSE_CATEGORIES: ExpenseCategoryItem[] = [
  { name: "Housing", amount: 22000, percentage: 40.5, color: "#8b5cf6", isEssential: true },
  { name: "Food", amount: 12500, percentage: 23.0, color: "#ec4899", isEssential: true },
  { name: "Transport", amount: 5400, percentage: 10.0, color: "#3b82f6", isEssential: true },
  { name: "Shopping", amount: 4800, percentage: 8.8, color: "#f59e0b", isEssential: false },
  { name: "Subscriptions", amount: 2340, percentage: 4.3, color: "#10b981", isEssential: false },
  { name: "Entertainment", amount: 3200, percentage: 5.9, color: "#06b6d4", isEssential: false },
  { name: "Utilities", amount: 2800, percentage: 5.2, color: "#6366f1", isEssential: true },
  { name: "Other", amount: 1160, percentage: 2.3, color: "#64748b", isEssential: false },
];

export const MOCK_GOALS: GoalItem[] = [
  {
    id: "goal-1",
    title: "Emergency Fund",
    targetAmount: 150000,
    currentAmount: 72000,
    monthlyContribution: 10000,
    targetDate: "May 2027",
    category: "Safety Buffer",
    color: "#8b5cf6",
  },
  {
    id: "goal-2",
    title: "Vacation Trip to Bali",
    targetAmount: 120000,
    currentAmount: 45000,
    monthlyContribution: 8000,
    targetDate: "Nov 2026",
    category: "Leisure",
    color: "#ec4899",
  },
  {
    id: "goal-3",
    title: "MacBook Pro Upgrade",
    targetAmount: 200000,
    currentAmount: 110000,
    monthlyContribution: 12000,
    targetDate: "Dec 2026",
    category: "Gadgets",
    color: "#3b82f6",
  },
  {
    id: "goal-4",
    title: "Car Down Payment",
    targetAmount: 300000,
    currentAmount: 85000,
    monthlyContribution: 15000,
    targetDate: "Aug 2027",
    category: "Vehicle",
    color: "#10b981",
  },
];

export const MOCK_AI_INSIGHTS: AIInsightItem[] = [
  {
    id: "insight-1",
    title: "Food Spending Alert",
    description: "Food spending is 23% higher than your 3-month average. Cutting dining out could save ₹3,200 monthly.",
    category: "warning",
    impact: "+ ₹3,200/mo savings",
    icon: "Utensils",
  },
  {
    id: "insight-2",
    title: "Recurring Subscriptions Review",
    description: "You have 3 recurring subscriptions costing approximately ₹2,340/month. YouTube Premium has low engagement.",
    category: "tip",
    impact: "Potential ₹129/mo cut",
    icon: "Tv",
  },
  {
    id: "insight-3",
    title: "Emergency Fund Strategy",
    description: "Your current monthly surplus (₹30,800) can comfortably support a ₹10,000 emergency-fund contribution without altering lifestyle.",
    category: "opportunity",
    impact: "Reach target in 8 mos",
    icon: "ShieldCheck",
  },
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "alert-1",
    title: "Upcoming EMI Due",
    message: "Home Loan EMI of ₹18,500 due on 15th Sep from HDFC Bank Account.",
    priority: "HIGH",
    type: "emi_due",
    date: "Sep 15, 2026",
  },
  {
    id: "alert-2",
    title: "Large Transaction Detected",
    message: "₹14,999 spent at Electronics Hub on HDFC Credit Card.",
    priority: "MEDIUM",
    type: "large_transaction",
    date: "Sep 09, 2026",
  },
  {
    id: "alert-3",
    title: "Overspending Warning",
    message: "Shopping budget reached 92% of monthly allocated threshold.",
    priority: "HIGH",
    type: "overspending",
    date: "Sep 08, 2026",
  },
  {
    id: "alert-4",
    title: "Subscription Renewal",
    message: "Netflix annual subscription (₹649/mo) renews automatically in 3 days.",
    priority: "LOW",
    type: "subscription_renewal",
    date: "Sep 14, 2026",
  },
  {
    id: "alert-5",
    title: "Low Cash Buffer Risk",
    message: "ICICI Savings balance near minimum threshold after rent transfer.",
    priority: "MEDIUM",
    type: "low_cash_buffer",
    date: "Sep 05, 2026",
  },
];

export const MOCK_TRANSACTIONS: TransactionItem[] = [
  {
    id: "tx-1",
    date: "2026-09-10",
    merchant: "Swiggy / Zomato",
    description: "Weekend Food Delivery",
    category: "Food",
    account: "ICICI Savings",
    type: "EXPENSE",
    amount: 850,
  },
  {
    id: "tx-2",
    date: "2026-09-09",
    merchant: "Tech Solutions Pvt Ltd",
    description: "Monthly Salary Credit",
    category: "Salary",
    account: "HDFC Salary Account",
    type: "INCOME",
    amount: 85000,
  },
  {
    id: "tx-3",
    date: "2026-09-08",
    merchant: "Electronics Hub",
    description: "Monitor Stand & Cables",
    category: "Shopping",
    account: "HDFC Credit Card",
    type: "EXPENSE",
    amount: 14999,
  },
  {
    id: "tx-4",
    date: "2026-09-05",
    merchant: "Apartment Landlord",
    description: "Monthly Apartment Rent",
    category: "Housing",
    account: "HDFC Salary Account",
    type: "EXPENSE",
    amount: 22000,
  },
  {
    id: "tx-5",
    date: "2026-09-03",
    merchant: "Netflix India",
    description: "Ultra HD Premium Plan",
    category: "Subscriptions",
    account: "HDFC Credit Card",
    type: "EXPENSE",
    amount: 649,
    isRecurring: true,
  },
  {
    id: "tx-6",
    date: "2026-09-02",
    merchant: "Uber Auto",
    description: "Commute to Client Office",
    category: "Transport",
    account: "ICICI Savings",
    type: "EXPENSE",
    amount: 320,
  },
  {
    id: "tx-7",
    date: "2026-09-01",
    merchant: "Spotify India",
    description: "Individual Music Sub",
    category: "Subscriptions",
    account: "HDFC Credit Card",
    type: "EXPENSE",
    amount: 119,
    isRecurring: true,
  },
  {
    id: "tx-8",
    date: "2026-08-30",
    merchant: "YouTube Premium",
    description: "Ad-free Media Streaming",
    category: "Subscriptions",
    account: "HDFC Credit Card",
    type: "EXPENSE",
    amount: 129,
    isRecurring: true,
  },
  {
    id: "tx-9",
    date: "2026-08-28",
    merchant: "State Electricity Board",
    description: "August Power Bill",
    category: "Utilities",
    account: "ICICI Savings",
    type: "EXPENSE",
    amount: 1840,
  },
  {
    id: "tx-10",
    date: "2026-08-25",
    merchant: "Freelance Client (US)",
    description: "UI Design Consulting",
    category: "Freelance",
    account: "HDFC Salary Account",
    type: "INCOME",
    amount: 12500,
  },
];

export const MOCK_LIABILITIES: LiabilityItem[] = [
  {
    id: "liab-1",
    name: "Home Loan",
    outstanding: 520000,
    interestRate: 8.5,
    emi: 18500,
    type: "Secured Mortgage",
    recommendationNote: "Maintain steady EMIs. Low interest rate makes this safe to service long-term.",
  },
  {
    id: "liab-2",
    name: "Credit Card Outstanding",
    outstanding: 48000,
    interestRate: 36.0,
    emi: 4250,
    minimumDue: 4250,
    type: "Unsecured Revolving",
    recommendationNote: "CRITICAL: 36% APR is consuming ₹1,440/mo in interest alone! Prioritize paying full ₹48,000 using monthly surplus.",
  },
  {
    id: "liab-3",
    name: "Personal Loan",
    outstanding: 72000,
    interestRate: 12.5,
    emi: 3800,
    type: "Unsecured Term Loan",
    recommendationNote: "Pay off immediately after credit card debt is cleared to save ₹9,000 in remaining interest.",
  },
];

export const MOCK_SUBSCRIPTIONS: SubscriptionItem[] = [
  {
    id: "sub-1",
    name: "Netflix",
    amount: 649,
    billingCycle: "monthly",
    nextBilling: "2026-09-14",
    category: "Entertainment",
    status: "active",
  },
  {
    id: "sub-2",
    name: "Spotify",
    amount: 119,
    billingCycle: "monthly",
    nextBilling: "2026-10-01",
    category: "Music",
    status: "active",
  },
  {
    id: "sub-3",
    name: "YouTube Premium",
    amount: 129,
    billingCycle: "monthly",
    nextBilling: "2026-09-30",
    category: "Streaming",
    isDetectedRecently: true,
    status: "saving_opportunity",
  },
  {
    id: "sub-4",
    name: "Amazon Prime",
    amount: 1499,
    billingCycle: "yearly",
    nextBilling: "2026-12-15",
    category: "Shopping / Video",
    status: "active",
  },
  {
    id: "sub-5",
    name: "Gym Membership",
    amount: 1500,
    billingCycle: "monthly",
    nextBilling: "2026-09-20",
    category: "Health & Fitness",
    status: "flagged",
  },
];

export const MOCK_CHAT_SUGGESTIONS = [
  "Can I afford a ₹25,000 phone?",
  "How much should I save this month?",
  "Which debt should I pay first?",
  "Where am I overspending?",
];

export const MOCK_INITIAL_CHAT: ChatMessage[] = [
  {
    id: "msg-1",
    sender: "assistant",
    text: "Hello Alex! 👋 I'm your **FinPilot AI** personal advisor. I've analyzed your financial health score (78/100), active liabilities, and income streams. How can I assist your financial goals today?",
    timestamp: "10:30 AM",
    suggestedActions: MOCK_CHAT_SUGGESTIONS,
  },
];
